# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/binford.yml

## desktop environments

  - include_tasks: desktop_environments/mate/appearance.yml
    when: mate is defined and mate == true


  ## system setup
  - import_tasks: system_setup/scripts.yml

  ## install software
  - import_tasks: software/chromium.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/steam.yml

  rescue:
    - set_fact: task_failed=true

