- name: server setup | stuff | install packages
  tags: packages,server,settings
  package:
    state: latest
    name:
      - apt-listbugs
      - auditd
      - debsums
      - debsecan
      - chkrootkit
      - clamav
      - fail2ban
      - logrotate
      - lynis
      - needrestart
      - pkg-config
      - docker.io

- name: Install Python Docker Module
  pip:
    name: docker
    state: present

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
