- name: system setup | utilities | install utility packages
  tages: packages,system,settings
  package:
    state: latest
    name:
      - ed
      - curl
      - htop
      - tmux
      - vim
      - vifm
      - wget
      - wget
      - xclip
      - python3
      - python3-pip
      - fping
      - iptables
      - iptables-persistent
      - net-tools
      - nmap
      - nslookup
      - tracerout

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,setttings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
