- name: ufw | install package
  tags: ufw
  package:
    state: latest
    name: ufw
  notify:
    - restart_ufw

# dns
- name: ufw | dns | allow dns (tcp)
  tags: ufw
  ufw:
    comment: dns
    rule: allow
    port: '53'
    proto: tcp
  when:
    - dns_server is defined
    - dns_server == true

- name: ufw | dns | allow dns (udp)
  tags: ufw
  ufw:
    comment: dns
    rule: allow
    port: '53'
    proto: udp
  when:
    - dns_server is defined
    - dns_server == true

# openssh
- name: ufw | openssh | allow ssh (external)
  tags: ufw
  ufw:
    comment: ssh from home network
    rule: allow
    port: ssh
    src: ip*.and.59.rng/32
  when:
    - web_instance is defined
    - web_instance == true

- name: ufw | openssh | allow ssh (internal)
  tags: ufw
  ufw:
    comment: ssh
    rule: allow
    port: ssh
    src: '{{ item }}'
  loop:
    - **.**.**.**/**
    - ***.**.***.*/**
    - ***.**.***.*/**
    - ***.**.***.*/**
    - ***.**.***.*/**
  when:
    - web_instance is defined
    - web_instance == false

# web server
- name: ufw | web server | allow http (80)
  tags: ufw
  ufw:
    comment: http
    rule: allow
    port: '80'
    proto: tcp
  when:
    - web_server is defined
    - web_server == true

- name: ufw | web server | allow http (8080)
  tags: ufw
  ufw:
    comment: http_8080
    rule: allow
    port: '8080'
    proto: tcp
  when:
    - web_server_8080 is defined
    - web_server_8080 == true

- name: ufw | web server | allow https
  tags: ufw
  ufw:
    comment: https
    rule: allow
    port: '443'
    proto: tcp
  when:
    - web_server is defined
    - web_server == true

# all rules set, enable
- name: ufw | enable firewall
  ufw:
    state: enabled

