- name: system setup | scripts | copy image_prep.sh script
  tags: scripts
  copy:
    src: system_setup/image_prep.sh
    dest: /usr/local/bin/image_prep.sh
    owner: root
    group: root
    mode: 0755
    
- name: system setup | scripts | copy cleanup.sh
  tags: scripts,cron
  copy:
    src: system_setup/cleanup.sh
    dest: /etc/cron.daily/cleanup.sh
    owner: root
    group: root
    mode: 0600

- name: system setup | scripts | copy update.sh
  tags: scripts,cron
  copy:
    src: system_setup/update.sh
    dest: /etc/cron.weekly/update.sh
    owner: root
    group: root
    mode: 0600
